src/channel.c: drop conflicting 'on_channel_created_cb' definition
On gcc-10 services fail to build as:

```
  ld: services-interface.o:src/interface.c:89:
    multiple definition of `on_channel_created_cb';
    services-channel.o:src/channel.c:53: first defined here
```

It is exposed by a gcc-10 change to default to `fno-common`:
  https://gcc.gnu.org/gcc-10/porting_to.html

I dropped `on_channel_created_cb` definition in `src/channel.c`
as it does not seem to be used there.

Signed-off-by: Sergei Trofimovich <slyfox@gentoo.org>